name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Netlify
        run: npm install netlify-cli@17.22.1 -g

      - name: Prettier
        run: npm run prettier

      # - name: Lint
      #   run: npm run lint

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test

      - name: Deploy to Netlify
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            --prod
