name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Set environment variable
        env:
          VITE_ANALYTICS_ID: ${{ secrets.VITE_ANALYTICS_ID }}
        run: |
          echo "VITE_ANALYTICS_ID=${{ secrets.VITE_ANALYTICS_ID }}" >> $GITHUB_ENV

      - name: Install Netlify
        run: npm install netlify-cli@18.0.2 -g

      - name: Prettier
        run: npm run prettier

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test:coverage

      - name: Deploy to Netlify
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && '--prod' || '' }}
